USE [master]
GO

/****** Object:  Database [Dream]    Script Date: 19.10.2021 15:18:40 ******/
CREATE DATABASE [Dream]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Dream', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Dream.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Dream_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Dream_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Dream].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Dream] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Dream] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Dream] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Dream] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Dream] SET ARITHABORT OFF 
GO

ALTER DATABASE [Dream] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Dream] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Dream] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Dream] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Dream] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Dream] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Dream] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Dream] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Dream] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Dream] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Dream] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Dream] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Dream] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Dream] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Dream] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Dream] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Dream] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Dream] SET RECOVERY FULL 
GO

ALTER DATABASE [Dream] SET  MULTI_USER 
GO

ALTER DATABASE [Dream] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Dream] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Dream] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Dream] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Dream] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Dream] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Dream] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Dream] SET  READ_WRITE 
GO

